### ISSUE TITLE
Use ink for CLI

### ISSUE THREAD

**Issue by AriPerkkio** [AriPerkkio/eslint-remote-tester#1]
Current implementation of `log-renderer.ts` works well but is difficult to maintain and test. Replace this with [ink](https://github.com/vadimdemedes/ink).

However after first try with ink it seems to cause flickering output. This is most probably caused by ink's `console.clear`, `process.stdout.clearLine` or `process.stdout.write` calls. It seems to be updating whole screen instead of only the changed parts.

<img src="https://user-images.githubusercontent.com/14806298/97105257-2ed35380-16c2-11eb-8d9f-70a812d93c30.gif" height="480"/>

Custom `log-renderer.ts` handles updates better by only updating required parts of the screen.
<img src="https://user-images.githubusercontent.com/14806298/97105273-44487d80-16c2-11eb-86da-e1f0d5e498f6.gif" height="480"/>

Possible solutions:
1. Check if ink exposes stdout and process its calls with `log-diff.ts` before actual writes
2. Check if `log-diff.ts` could be implemented into ink itself
3. Forget about ink and figure out how to test `log-renderer.ts` easily

**Comment by AriPerkkio** [comment]
Ink clears terminal between each update using `ansi-escapes`:
https://github.com/vadimdemedes/ink/blob/c83a5d0ab3e95a8d30d70bc466808e567727eb97/src/log-update.ts#L27-L29

`log-renderer.ts` updates only the required parts:
https://github.com/AriPerkkio/eslint-remote-tester/blob/015a78cef87d371079d4a5842c5905e1b9cdf063/lib/progress-logger/log-renderer.ts#L343-L356

Ping to @vadimdemedes, have you ever thought about this kind of terminal updating to ink - so that only the required parts of the screen are updated?

**Comment by vadimdemedes** [comment]
How can I reproduce the flickering? It may be due to specifics of each terminal app.

**Comment by AriPerkkio** [comment]
It indeed seems to be caused by the terminal, thanks for the tip. The flickering was seen on VSCode's integrated terminal (xterm.js implementation) and ChromeOS crostini's Debian 9's xterm. I quickly tested gnome-terminal and hyper on Debian, and git-bash, cmd and powershell on windows. They all seem to work without flickering as long as rendering updates are locked to ~200ms. 

Replacing current custom `log-renderer.ts` with ink seems to be possible without applying any hacks mentioned in opening post.

**Comment by vadimdemedes** [comment]
Yep, those terminals integrated into the apps often don't have the best performance.
