### ISSUE TITLE
Report crashing rules to ESLint community plugins

### ISSUE THREAD

**Issue by AriPerkkio** [AriPerkkio/eslint-remote-tester#3]
In order to have some long term statistics let's keep a list of findings.

- `no-useless-constructor: Cannot read property 'body' of null` https://github.com/eslint/eslint/issues/13830
- `Bug: eslint-plugin-react-hooks: Cannot read property 'type' of undefined at analyzePropertyChain` https://github.com/facebook/react/issues/20204
- Unreleased: `Add new rule "react/no-referential-type-default-prop"` https://github.com/yannickcr/eslint-plugin-react/pull/2848
- `import-style: Cannot read property 'type' of undefined` https://github.com/sindresorhus/eslint-plugin-unicorn/issues/902
- `prefer-query-selector: Cannot read property 'type' of undefined` https://github.com/sindresorhus/eslint-plugin-unicorn/issues/903
- `prefer-to-have-style: Cannot read property 'range' of undefined` https://github.com/testing-library/eslint-plugin-jest-dom/issues/97
- `[method-signature-style] Cannot read property 'typeAnnotation' of undefined #2834` https://github.com/typescript-eslint/typescript-eslint/issues/2834
- `prevent-abbreviations: Fix objects must not be overlapped in a report.` https://github.com/sindresorhus/eslint-plugin-unicorn/issues/912
- `jsx-no-script-url: Cannot read property 'type' of null` https://github.com/yannickcr/eslint-plugin-react/issues/2871
- `no-typos: Cannot read property 'toLowerCase' of undefined` https://github.com/yannickcr/eslint-plugin-react/issues/2870
- `jsx-max-depth: Cannot read property 'length' of undefined` https://github.com/yannickcr/eslint-plugin-react/issues/2869
- `useSelector-prefer-selectors: Cannot read property 'type' of undefined` https://github.com/DianaSuvorova/eslint-plugin-react-redux/issues/59
- `no-unused-prop-types: Cannot read property 'name' of null` https://github.com/DianaSuvorova/eslint-plugin-react-redux/issues/58
- `no-force: Cannot read property 'name' of undefined` https://github.com/cypress-io/eslint-plugin-cypress/issues/71
- `no-unnecessary-waiting: Cannot read property 'undefined' of undefined` https://github.com/cypress-io/eslint-plugin-cypress/issues/72
- `createBannedAttributeRule: Cannot destructure property 'object' of 'undefined' or 'null'` https://github.com/testing-library/eslint-plugin-jest-dom/issues/127
- `jsx-wrap-multilines: RangeError: Invalid count value` https://github.com/yannickcr/eslint-plugin-react/issues/2875
- `prefer-default-export: Cannot read property 'type' of null` https://github.com/benmosher/eslint-plugin-import/issues/1965
- `prefer-wait-for: Cannot read property 'arguments' of null` https://github.com/testing-library/eslint-plugin-testing-library/issues/272
- `no-manual-cleanup: Cannot read property 'match' of undefined` https://github.com/testing-library/eslint-plugin-testing-library/issues/273
- `mapStateToProps-prefer-hoisted: Cannot read property 'type' of null` https://github.com/DianaSuvorova/eslint-plugin-react-redux/issues/63
- `no-unknown-property: allowedTags.indexOf is not a function` https://github.com/yannickcr/eslint-plugin-react/issues/2879
- `jsx-max-depth: Maximum call stack size exceeded` https://github.com/yannickcr/eslint-plugin-react/issues/2880
- `[comma-spacing] Cannot read property 'range' of undefined` https://github.com/typescript-eslint/typescript-eslint/issues/2906
- `jsx-no-constructed-context-values: Cannot read property 'set' of undefined` https://github.com/yannickcr/eslint-plugin-react/issues/2894
- `jsx-no-constructed-context-values: Cannot read property 'type' of null` https://github.com/yannickcr/eslint-plugin-react/issues/2895
- `role-supports-aria-props: Cannot read property 'expression' of undefined` https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/770
- `no-dupe-characters-character-class: Incompatible flags: The i flag is forbidden to create a literal but required by the options.` https://github.com/ota-meshi/eslint-plugin-regexp/issues/189
- `[prefer-readonly-parameter-types] Maximum call stack size exceeded` https://github.com/typescript-eslint/typescript-eslint/issues/3396
- `[prefer-readonly-parameter-types] Cannot read property 'flags' of undefined` https://github.com/typescript-eslint/typescript-eslint/issues/3405
- `no-deprecated: Cannot read property 'name' of undefined` https://github.com/yannickcr/eslint-plugin-react/issues/3016
- `prefer-user-event: Cannot read property 'value' of undefined` https://github.com/testing-library/eslint-plugin-testing-library/issues/405
- `no-typos: TypeError: only function nodes are expected` https://github.com/yannickcr/eslint-plugin-react/issues/3036
- `no-html-link-for-pages: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined` https://github.com/vercel/next.js/issues/28030
- `no-namespace: TypeError: Cannot read property 'indexOf' of null` https://github.com/yannickcr/eslint-plugin-react/issues/3082
- `[prefer-regexp-exec] Cannot read property 'type' of undefined` https://github.com/typescript-eslint/typescript-eslint/issues/3941
- `no-legacy-features: Error while loading rule 'regexp/no-legacy-features': Debug Failure` https://github.com/ota-meshi/eslint-plugin-regexp/issues/378
- Bug: `no-restricted-exports`: Cannot read property 'name' of null https://github.com/eslint/eslint/issues/15384

**Comment by ljharb** [comment]
It'd be great if you could also run against eslint-plugin-import and eslint-plugin-jsx-a11y (also, eslint-config-airbnb and eslint-config-airbnb-base).

**Comment by AriPerkkio** [comment]
`eslint-plugin-jsx-a11y` is included in the weekly scheduled CI runs. 

https://github.com/AriPerkkio/eslint-remote-tester/blob/a06bf856c29f7cd21e335d989a8ead7ba0f15ea7/ci/plugin-configs/eslint-plugin-jsx-a11y.config.js#L7

Last week it ran the `recommended` rules successfully against ~1800 repositories. https://github.com/AriPerkkio/eslint-remote-tester/runs/1506856620?check_suite_focus=true

I'll add those other plugins as well. I think some rules of the `eslint-plugin-import` cannot be enabled. Only purely static analysis can be done as the linter is ran against file contents only.
