### ISSUE TITLE
 doesn't work as expected

### ISSUE THREAD

**Issue by andriyor** [AriPerkkio/eslint-remote-tester#543]
testing on this repo https://github.com/staeco/iris-ql

rules works by installing them directly on project

<img width="1681" alt="image" src="https://github.com/user-attachments/assets/00dcae1e-bbb1-4dd3-ae1e-29924b458eb0">

but i don't have any errors with eslint-remote-tester

<img width="844" alt="image" src="https://github.com/user-attachments/assets/43d5ecae-14b4-4919-bf64-98ca275b3c65">

repo: https://github.com/andriyor/eslint-remote-tester-example/blob/main/eslint-remote-tester.config.js

**Comment by AriPerkkio** [comment]
Does adding `rulesUnderTesting: (ruleId: string) => true` help?

https://github.com/AriPerkkio/eslint-remote-tester/blob/dd0d3056fba0f2efb15362a810433a7c29511a97/README.md?plain=1#L94

By default only ESLint rule crashes are reported. Using `rulesUnderTesting` you can filter which rule errors should be reported as well.

**Comment by andriyor** [comment]
thanks, it helped
now i see how many errors have each repo, but how can i see error logs to understand which rule failed and file path?

**Comment by AriPerkkio** [comment]
There should be `./eslint-remote-tester-results` written after run.

https://github.com/AriPerkkio/eslint-remote-tester/blob/dd0d3056fba0f2efb15362a810433a7c29511a97/README.md?plain=1#L111-L113

**Comment by andriyor** [comment]
Ohh, thank you, sorry for bothering
Do you have some kind of API to use this tool programmatically?

**Comment by AriPerkkio** [comment]
There's `onComplete` that can be used to get access to the results after run is finished. Does this work for you?

https://github.com/AriPerkkio/eslint-remote-tester/blob/dd0d3056fba0f2efb15362a810433a7c29511a97/README.md?plain=1#L104

Example arguments that are passed there:

https://github.com/AriPerkkio/eslint-remote-tester/blob/dd0d3056fba0f2efb15362a810433a7c29511a97/docs/onComplete-arguments.json#L2-L23
